---
title: "How to cite"
output: html_document
---

<style>
body {
text-align: justify}
</style>

## **How to cite GLOSSA**

Thank you for using GLOSSA! Tu cite our app, please use the following references.

#### GLOSSA GitHub repository

The GLOSSA paper is currently in progress. Meanwhile, you can reference the GitHub repository as follows:

> Mestre-Tomás, J., Fuster-Alonso, A., & Coll, M. (2024) GLOSSA: A user-friendly Shiny app for global spatiotemporal analysis of species with BART machine learning model. Retrieved from <a href="https://github.com/jmestret/glossa" target="_blank">github.com/jmestret/glossa</a>.

#### BART model reference

If you use the BART model in your work, please also cite the original paper:

> Chipman, H. A., George, E. I., & McCulloch, R. E. (2010). BART: Bayesian Additive Regression Trees. *The Annals of Applied Statistics*, 4(1), 266–298.

and if use BART on a global-scale, please include this citation:

> Fuster-Alonso, A., Mestre-Tomás, J., Baez, J. C., Pennino, M. G., Barber, X., Bellido, J. M., ... & Coll, M. (2024). Machine learning applied to global scale species distribution models (SDMs). PREPRINT (Version 1) available at Research Square <a href="https://doi.org/10.21203/rs.3.rs-4411399/v1" target="_blank">doi.org/10.21203/rs.3.rs-4411399/v1</a>.
